### ISSUE TITLE
Can readProperty but can't writeProperty

### ISSUE THREAD

**Issue by Panibrat** [fh1ch/node-bacstack#58] opened 2017-09-03 11:45 UTC
Read function works fine:
Code:
client.readProperty('192.168.0.127', 2, 3000052, 85, null, function(err, value) {
    console.log('readPropertyAV: ', value);
});
Console:
readPropertyAV:  { len: 14,
  objectId: { type: 2, instance: 3000052 },
  property: { propertyIdentifier: 85, propertyArrayIndex: 4294967295 },
  valueList: [ { len: 5, type: 4, value: 12.6 } ] }

But I can't write the same point:

Code:
client.writeProperty('192.168.0.127', 2, 3000052, 85, 12, [
    {type: bacnet.enum.BacnetApplicationTags.BACNET_APPLICATION_TAG_REAL, value: 77}
], function(err, value) {
    console.log('writeProperty: ', value);
    console.log('writePropertyError: ', err);
});
Console:
D:\PANIBRAT\WEB-2\NodeJS\BACnet\test\node_modules\bacstack\lib\bacnet-asn1.js:496
      throw 'Unknown type';
      ^
Unknown type

What wrong?
Any suggestions?

**Comment by fh1ch** [comment] 2017-09-03 12:14
Hi @Panibrat 

Thanks for reporting an issue 👍 

The error message is generated by node-bacstack itself if he is not able to encode a write-property telegram. 

The root cause for this issue is a breaking change, which is not yet available on NPM but already updated in the documentation (see https://github.com/fh1ch/node-bacstack/commit/35a46ce3b7090700af21b8bcc0c9d6e9f21339ac). Could you therefore change your code as following and retry it:

```js
client.writeProperty('192.168.0.127', 2, 3000052, 85, 12, [
{tag: bacnet.enum.BacnetApplicationTags.BACNET_APPLICATION_TAG_REAL, value: 77}
], function(err, value) { // NOTE: `type` changed to `tag`
console.log('writeProperty: ', value);
console.log('writePropertyError: ', err);
});
```

This issue/inconsistency should be solved in the upcoming `beta.10` release in a couple of day.

Thanks!

**Comment by Panibrat** [comment] 2017-09-03 13:19
Now it works! :)

**Comment by Panibrat** [comment] 2017-09-03 14:50
The same issue with Binary Value:
Code:

```
client.readProperty('192.168.0.222', 5, 11, 104, null, function(err, value) {
    console.log('readPropertyBV: ', value);
});

```
Console:
```
readPropertyBV:  { len: 11,
  objectId: { type: 5, instance: 11 },
  property: { propertyIdentifier: 104, propertyArrayIndex: 4294967295 },
  valueList: [ { len: 2, type: 9, value: 1 } ] }
```

Try to write:
Code:
`client.writeProperty('192.168.0.222', 5, 11, 104, 12, [
    {tag: bacnet.enum.BacnetApplicationTags.BACNET_APPLICATION_TAG_UNSIGNED_INT, value: 0}
], function(err, value) { // NOTE: `type` changed to `tag`
    console.log('writeProperty: ', value);
    if(err){
        console.log('writePropertyError: ', err);
    }
});`
Console:
```
writeProperty:  undefined
writePropertyError:  Error: BacnetError - Class:2 - Code:9
    at processError (D:\PANIBRAT\WEB-2\NodeJS\BACnet\test\node_modules\bacstack\lib\bacnet-client.js:71:30)
    at handlePdu (D:\PANIBRAT\WEB-2\NodeJS\BACnet\test\node_modules\bacstack\lib\bacnet-client.js:201:9)
    at handleNpdu (D:\PANIBRAT\WEB-2\NodeJS\BACnet\test\node_modules\bacstack\lib\bacnet-client.js:235:5)
    at self.receiveData (D:\PANIBRAT\WEB-2\NodeJS\BACnet\test\node_modules\bacstack\lib\bacnet-client.js:246:7)
    at Socket.<anonymous> (D:\PANIBRAT\WEB-2\NodeJS\BACnet\test\node_modules\bacstack\lib\bacnet-transport.js:13:25)
    at emitTwo (events.js:106:13)
    at Socket.emit (events.js:191:7)
    at UDP.onMessage (dgram.js:548:8)

```
Please advise!

**Comment by fh1ch** [comment] 2017-09-03 17:51
Hi @Panibrat 

The two exceptions `BacnetError` and `BacnetAbort` are errors on application level, meaning both node-bacstack and your device are working propperly, but something in your code is wrong. This error can be interpreted by taking a look at [BacnetErrorClasses](https://github.com/fh1ch/node-bacstack/blob/master/lib/bacnet-enum.js#L102) and [BacnetErrorCodes](https://github.com/fh1ch/node-bacstack/blob/master/lib/bacnet-enum.js#L116), in your case `ERROR_CLASS_PROPERTY - ERROR_CODE_INVALID_DATA_TYPE`, which means you're trying to write a BACNET property with a wrong data type.

If we compare the console output of your readProperty command (`valueList: [ { len: 2, type: 9, value: 1 } ]`) with the writeProperty command `[ {tag: bacnet.enum.BacnetApplicationTags.BACNET_APPLICATION_TAG_UNSIGNED_INT, value: 0} ]`, we see that type `9` is actually [BACNET_APPLICATION_TAG_ENUMERATED](https://github.com/fh1ch/node-bacstack/blob/master/lib/bacnet-enum.js#L743). You therefore have to adapt your code to:

```js
client.writeProperty('192.168.0.222', 5, 11, 104, 12, [ {tag: bacnet.enum.BacnetApplicationTags.BACNET_APPLICATION_TAG_ENUMERATED, value: 0} ], function(err, value) { // NOTE: type changed to correct value
  console.log('writeProperty: ', value); 
  if(err) { console.log('writePropertyError: ', err); } 
});
```

This should then be accepted by your device.

I will therefore close this issue, feel free to re-open it if something is still not working.

Cheers

**Closed by fh1ch** 2017-09-03 17:51 UTC
Labels: awaiting-feedback, bug

**Comment by Panibrat** [comment] 2017-09-03 18:46
Everything OK for now!
Thank you!
